FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y libelf-dev && \
    apt-get install -y make && \
    apt-get install -y gcc


WORKDIR /app
COPY . .

ENTRYPOINT [ "sleep", "infinity" ]
